## Introduction to Pandas

Pandas is a newer package built on top of NumPy, and provides an
efficient implementation of a DataFrame . DataFrame s are essentially multidimen‐
sional arrays with attached row and column labels, and often with heterogeneous
types and/or missing data. As well as offering a convenient storage interface for
labeled data, Pandas implements a number of powerful data operations familiar to
users of both database frameworks and spreadsheet programs.

As we saw, NumPy’s ndarray data structure provides essential features for the type of
clean, well-organized data typically seen in numerical computing tasks. While it
serves this purpose very well, its limitations become clear when we need more flexi‐
bility (attaching labels to data, working with missing data, etc.) and when attempting
operations that do not map well to element-wise broadcasting (groupings, pivots,
etc.), each of which is an important piece of analyzing the less structured data avail‐
able in many forms in the world around us.

Pandas, and in particular its Series and
DataFrame objects, builds on the NumPy array structure and provides efficient access
to these sorts of “data munging” tasks that occupy much of a data scientist’s time.

In [1]:
import pandas as pd
pd.__version__

'0.25.3'

In [2]:
import numpy as np
import pandas as pd

#### The Pandas Series Object

A Pandas Series is a one-dimensional array of indexed data.

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The Series wraps both a sequence of values and a
sequence of indices, which we can access with the values and index attributes.

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

Like with a NumPy array, data can be accessed by the associated index via the familiar
Python square-bracket notation

In [6]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

It may look like the Series object is basically inter‐
changeable with a one-dimensional NumPy array. The essential difference is the pres‐
ence of the index: while the NumPy array has an implicitly defined integer index used
to access the values, the Pandas Series has an explicitly defined index associated with
the values.

This explicit index definition gives the Series object additional capabilities. For
example, the index need not be an integer, but can consist of values of any desired
type.

In [8]:
## Syntax - pd.Series(data, index=index)

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

0.5

Pandas Series a bit like a specialization of a Python
dictionary. A dictionary is a structure that maps arbitrary keys to a set of arbitrary
values, and a Series is a structure that maps typed keys to a set of typed values. This
typing is important: just as the type-specific compiled code behind a NumPy array
makes it more efficient than a Python list for certain operations, the type information
of a Pandas Series makes it much more efficient than Python dictionaries for certain
operations.

We can make the Series as dictionary analogy even more clear by constructing a
Series object directly from a Python dictionary

In [9]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [10]:
population['California']

38332521

Unlike a dictionary, though, the Series also supports array-style operations such as
slicing

In [15]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
# population_dict['California':'Illinois']

In constructing Series objects, data can be a list, NumPy array or dictionary.

In [17]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [18]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [19]:
pd.Series(5)

0    5
dtype: int64

In [20]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### The Pandas DataFrame Object

The next fundamental structure in Pandas is the DataFrame . The DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.

#### DataFrame as a generalized NumPy array

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame
is an analog of a two-dimensional array with both flexible row indices and flexible
column names.

In [23]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [24]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [26]:
states = pd.DataFrame({'population': population,'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Like the Series object, the DataFrame has an index attribute that gives access to the
index labels

In [27]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the DataFrame has a columns attribute, which is an Index object holding
the column labels

In [28]:
states.columns

Index(['population', 'area'], dtype='object')

Thus the DataFrame can be thought of as a generalization of a two-dimensional
NumPy array, where both the rows and columns have a generalized index for access‐
ing the data.

#### DataFrame as specialized dictionary

A dictionary maps a key to a value, a DataFrame maps a column name to a Series of
column data.

In [25]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Notice the potential point of confusion here: in a two-dimensional NumPy array,
data[0] will return the first row. For a DataFrame , data['col0'] will return the first
column. Because of this, it is probably better to think about DataFrame s as generalized
dictionaries rather than generalized arrays, though both ways of looking at the situa‐
tion can be useful.

We can construct DataFrame objects in a variety of ways. Some of them are :-

##### From a single Series object

A DataFrame is a collection of Series objects, and a single-
column DataFrame can be constructed from a single Series

In [26]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

##### From a list of dict

Any list of dictionaries can be made into a DataFrame . We’ll use a
simple list comprehension to create some data

In [27]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(data)
pd.DataFrame(data)

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]


a  b
0  0  0
1  1  2
2  2  4

Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
“not a number”) values

In [29]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

##### From a dictionary of Series objects

In [30]:
pd.DataFrame({'population': population,'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

##### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can
create a DataFrame with any specified column and index names. If omitted, an integer
index will be used for each

In [31]:
pd.DataFrame(np.random.rand(3, 2),columns=['x', 'y'],index=['a', 'b', 'c'])

x         y
a  0.867064  0.933612
b  0.144380  0.218361
c  0.294172  0.382841

##### From a NumPy structured array

In [32]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [33]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

We have seen here that both the Series and DataFrame objects contain an explicit
index that lets you reference and modify data. This Index object is an interesting
structure in itself, and it can be thought of either as an immutable array (a mutable object can be changed after it is created, and an immutable object can’t.) or as an
ordered set (technically a multiset, as Index objects may contain repeated values).

In [35]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

The Index object in many ways operates like an array. For example, we can use stan‐
dard Python indexing notation to retrieve values or slices

In [36]:
ind[1]

3

In [37]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [38]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


One difference between Index objects and NumPy arrays is that indices are immutable—that is, they cannot be modified via the normal means

In [41]:
# ind[1] = 0

This immutability makes it safer to share indices between multiple DataFrame s and
arrays, without the potential for side effects from inadvertent index modification.

### Data Selection in Series

A Series object acts in many ways like a one-
dimensional NumPy array, and in many ways like a standard Python dictionary.

Like a dictionary, the Series object provides a mapping from a collection of keys to a
collection of values

In [45]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [46]:
data['b']

0.5

In [47]:
'a' in data

True

In [48]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [49]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

Series objects can even be modified with a dictionary-like syntax. Just as you can
extend a dictionary by assigning to a new key, you can extend a Series by assigning
to a new index value

In [50]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [51]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [52]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

Notice that when 
slicing with an explicit index (i.e., data['a':'c'] ), the final index is included in
the slice, while when you’re slicing with an implicit index (i.e., data[0:2] ), the final
index is excluded from the slice.

In [46]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [53]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

These slicing and indexing conventions can be a source of confusion. For example, if
your Series has an explicit integer index, an indexing operation such as data[1] will
use the explicit indices, while a slicing operation like data[1:3] will use the implicit
Python-style index.

In [55]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [56]:
# explicit index when indexing
data[1]

'a'

In [57]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides
some special indexer attributes that explicitly expose certain indexing schemes.

First, the loc attribute allows indexing and slicing that always references the explicit
index

In [51]:
data.loc[1]

'a'

In [52]:
data.loc[1:3]

1    a
3    b
dtype: object

In [63]:
# try
# data.loc[2]

The iloc attribute allows indexing and slicing that always references the implicit
Python-style index

In [64]:
data.iloc[1]

'b'

In [65]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [66]:
data.iloc[2]

'c'

In [70]:
#try
# data.iloc[5]

### Data Selection in DataFrame

A DataFrame acts in many ways like a two-dimensional or structured array,
and in other ways like a dictionary of Series structures sharing the same index

##### DataFrame as a dictionary

In [71]:
area = pd.Series({'California': 423967, 'Texas': 695662,'New York': 141297, 'Florida': 170312,'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,'New York': 19651127, 'Florida': 19552860,'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [72]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [73]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [61]:
data.area is data['area']

True

Though this is a useful shorthand, keep in mind that it does not work for all cases!
For example, if the column names are not strings, or if the column names conflict
with methods of the DataFrame , this attribute-style access is not possible. For example, the DataFrame has a pop() method, so data.pop will point to this rather than the
"pop" column

In [62]:
data.pop is data['pop']

False

In [63]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [64]:
data.pop

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

Like with the Series objects, this dictionary-style syntax can also be
used to modify the object, in this case to add a new column

In [80]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

This shows a preview of the straightforward syntax of element-by-element arithmetic
between Series objects

##### DataFrame as two-dimensional array

In [81]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

We can see this is familiar array-like. Hence we can do array like operatin on dataframe itself. For example, we can transpose the full DataFrame to swap rows and
columns

In [82]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [83]:
data.T.values[0]

array([423967., 695662., 141297., 170312., 149995.])

In [84]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

When it comes to indexing of DataFrame objects, however, it is clear that the
dictionary-style indexing of columns precludes our ability to simply treat it as a
NumPy array.Thus for array-style indexing, Pandas again uses
the loc , iloc. Using the iloc indexer, we can
index the underlying array as if it is a simple NumPy array (using the implicit
Python-style index), but the DataFrame index and column labels are maintained in
the result

In [85]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [86]:
# data

In [87]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In the loc indexer we can combine masking and fancy indexing

In [88]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

Any of these indexing conventions may also be used to set or modify values

In [89]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### Ufuncs: Index Preservation

Because Pandas is designed to work with NumPy, any NumPy ufunc will work on
Pandas Series and DataFrame objects.

In [94]:
import pandas as pd
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [95]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

If we apply a NumPy ufunc on either of these objects, the result will be another Pan‐
das object with the indices preserved

In [96]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [97]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

##### Index alignment in Series

In [99]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

Any item for which one or the other does not have an entry is marked with NaN , or
“Not a Number,” which is how Pandas marks missing data

If using NaN values is not the desired behavior, modify the fill value using
appropriate object methods in place of the operators

In [101]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

##### Index alignment in DataFrame

A similar type of alignment takes place for both columns and indices when you are
performing operations on DataFrame 

In [102]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [103]:
list("AB")

['A', 'B']

In [104]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [105]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

Notice that indices are aligned correctly irrespective of their order in the two objects,
and indices in the result are sorted.

In [84]:
fill = A.stack().mean()
print(fill)
A.add(B, fill_value=fill)

4.5


A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [107]:
A.stack()

0  A     1
   B    11
1  A     5
   B     1
dtype: int64

In [108]:
A.stack()

0  A     1
   B    11
1  A     5
   B     1
dtype: int64

In [109]:
#try
A.shape
A.ndim
A.stack().shape
# A.stack().ndim
# A.stack().mean()

(4,)

Operations between a DataFrame and
a Series are similar to operations between a two-dimensional and one-dimensional
NumPy array.

In [110]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [111]:
A[0]

array([3, 8, 2, 4])

In [89]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

According to NumPy’s broadcasting rules subtraction between a two-dimensional array and one of its rows is
applied row-wise.

In Pandas, the convention similarly operates row-wise by default

In [112]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [113]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [114]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [115]:
df.loc[0]

Q    3
R    8
S    2
T    4
Name: 0, dtype: int64

In [116]:
df.subtract(df.loc[0],axis = 1)

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [117]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [118]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

This preservation and alignment of indices and columns means that operations on
data in Pandas will always maintain the data context, which prevents the types of silly
errors that might come up when you are working with heterogeneous and/or mis‐
aligned data in raw NumPy arrays.

### Handling Missing Data

The difference between data found in many tutorials and data in the real world is that
real-world data is rarely clean and homogeneous. In particular, many interesting
datasets will have some amount of data missing. To make matters even more complicated, different data sources may indicate missing data in different ways.

Pandas uses the special floating-
point NaN value, and the Python None objects for missing data

None is a Python object, hence it cannot be
used in any arbitrary NumPy/Pandas array, but only in arrays with data type
'object'

In [97]:
import numpy as np
import pandas as pd

In [98]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

This dtype=object means that the best common type representation NumPy could
infer for the contents of the array is that they are Python objects.

The other missing data representation, NaN (acronym for Not a Number), is different;
it is a special floating-point value recognized by all systems that use the standard
IEEE floating-point representation

In [99]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [100]:
1 + np.nan

nan

In [101]:
0 * np.nan

nan

In [102]:
vals2.sum(), vals2.min(), vals2.max()

/home/omkar/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/home/omkar/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


(nan, nan, nan)

In [103]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

Keep in mind that NaN is specifically a floating-point value; there is no equivalent
NaN value for integers, strings, or other types.

##### NaN and None in Pandas

In [104]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

NaN and None both have their place, and Pandas is built to handle the two of them
nearly interchangeably, converting between them where appropriate. If we set a value in an integer array to
np.nan , Pandas will automatically be upcast to a floating-point type to accommodate the
NA

In [105]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [106]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

Notice that in addition to casting the integer array to floating point, Pandas automati‐
cally converts the None to a NaN value

#### Operating on Null Values

Pandas treats None and NaN as essentially interchangeable for indi‐
cating missing or null values. To facilitate this convention, there are several useful
methods for detecting, removing, and replacing null values in Pandas data structures.

Pandas data structures have two useful methods for detecting null data: isnull() and
notnull() . Either one will return a Boolean mask over the data.

In [107]:
data = pd.Series([1, np.nan, 'hello', None])

In [108]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [109]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [110]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

The isnull() and notnull() methods produce similar Boolean results for Data
Frames.

##### Dropping null values

In addition to the masking used before, there are the convenience methods, dropna()
(which removes NA values) and fillna() (which fills in NA values). For a Series ,
the result is straightforward

In [111]:
data.dropna()

0        1
2    hello
dtype: object

For a DataFrame , there are more options. Consider the following DataFrame

In [112]:
df = pd.DataFrame([[1,np.nan, 2],[2,3,5],[np.nan, 4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

We cannot drop single values from a DataFrame ; we can only drop full rows or full
columns. Depending on the application, you might want one or the other, so
dropna() gives a number of options for a DataFrame .
By default, dropna() will drop all rows in which any null value is present

In [113]:
df.dropna()

0    1  2
1  2.0  3.0  5

Alternatively, you can drop NA values along a different axis; axis=1 drops all col‐
umns containing a null value

In [114]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

But this drops some good data as well; you might rather be interested in dropping
rows or columns with all NA values, or a majority of NA values. This can be specified
through the how or thresh parameters, which allow fine control of the number of
nulls to allow through.
The default is how='any' , such that any row or column (depending on the axis key‐
word) containing a null value will be dropped. You can also specify how='all' , which
will only drop rows/columns that are all null values:

In [115]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [116]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

For finer-grained control, the thresh parameter lets you specify a minimum number
of non-null values for the row/column to be kept

In [117]:
df.dropna(axis='rows', thresh=2)

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

Here the first and last row have been dropped, because they contain only two non-
null values.

##### Filling null values

Sometimes rather than dropping NA values, you’d rather replace them with a valid
value.


In [118]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [119]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [120]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [121]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

For DataFrames, the options are similar, but we can also specify an axis along which
the fills take place

In [122]:
df = pd.DataFrame([[1,np.nan, 2],[2,3,5],[np.nan, 4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [123]:
df.fillna(method='ffill', axis=1)

0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [124]:
df.fillna(method='ffill', axis=0)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

### Hierarchical Indexing

It is useful to go beyond 1D and 2D array and store higher-dimensional data—that is, data indexed
by more than one or two keys.

In [125]:
import pandas as pd
import numpy as np

In [126]:
index = [('California', 2000), ('California', 2010),('New York', 2000), ('New York', 2010),('Texas', 2000), ('Texas', 2010)]

In [127]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [128]:
populations = [33871648, 37253956,18976457, 19378102,20851820, 25145561]
pop = pd.Series(populations, index=index)

In [129]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [130]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

The unstack() method will quickly convert a multiply-
indexed Series into a conventionally indexed DataFrame

In [131]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [132]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [133]:
pop_df = pd.DataFrame({'total': pop,'under18': [9267089, 9284094,4687374, 4318033,5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [234]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()
# print(type(f_u18))

year            2000      2010
state                         
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [232]:
# f_u18.stack()

This allows us to easily and quickly manipulate and explore even high-dimensional
data.

The most straightforward way to construct a multiply indexed Series or DataFrame
is to simply pass a list of two or more index arrays to the constructor.

In [135]:
df = pd.DataFrame(np.random.rand(4, 2),index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],columns=['data1', 'data2'])
df

data1     data2
a 1  0.805279  0.963632
  2  0.424990  0.740199
b 1  0.090990  0.814071
  2  0.875672  0.892436

Similarly, if you pass a dictionary with appropriate tuples as keys, Pandas will auto‐
matically recognize this and use a MultiIndex by default

In [136]:
data = {('California', 2000): 33871648,
('California', 2010): 37253956,
('Texas', 2000): 20851820,
('Texas', 2010): 25145561,
('New York', 2000): 18976457,
('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

For more flexibility in how the index is constructed, you can instead use the class
method constructors available in the pd.MultiIndex .

In [137]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [138]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [139]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [140]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [141]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In a DataFrame , the rows and columns are completely symmetric, and just as the rows
can have multiple levels of indices, the columns can have multiple levels as well.

In [142]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
names=['subject', 'type'])

In [143]:
index

MultiIndex(levels=[[2013, 2014], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['year', 'visit'])

In [144]:
columns

MultiIndex(levels=[['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=['subject', 'type'])

In [145]:
# mock some data
data = np.round(np.random.randn(4, 6), 1)
print(data)

[[ 0.1  0.9 -1.4 -1.2 -0.4  1.7]
 [-0.5  0.7  0.1  0.5  0.7 -0.2]
 [ 0.7  0.4  0.  -0.  -2.1 -0.4]
 [-0.1  0.1 -0.1 -1.   1.5 -0.2]]


In [146]:
data[:, ::2] *= 10

In [147]:
data

array([[  1. ,   0.9, -14. ,  -1.2,  -4. ,   1.7],
       [ -5. ,   0.7,   1. ,   0.5,   7. ,  -0.2],
       [  7. ,   0.4,   0. ,  -0. , -21. ,  -0.4],
       [ -1. ,   0.1,  -1. ,  -1. ,  15. ,  -0.2]])

In [148]:
data += 37

In [149]:
data

array([[38. , 37.9, 23. , 35.8, 33. , 38.7],
       [32. , 37.7, 38. , 37.5, 44. , 36.8],
       [44. , 37.4, 37. , 37. , 16. , 36.6],
       [36. , 37.1, 36. , 36. , 52. , 36.8]])

In [150]:
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      38.0  37.9  23.0  35.8  33.0  38.7
     2      32.0  37.7  38.0  37.5  44.0  36.8
2014 1      44.0  37.4  37.0  37.0  16.0  36.6
     2      36.0  37.1  36.0  36.0  52.0  36.8

This is fundamentally four-dimensional data, where the dimensions are the
subject, the measurement type, the year, and the visit number. With this in place we
can, for example, index the top-level column by the person’s name and get a full Data
Frame containing just that person’s information

In [151]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      23.0  35.8
     2      38.0  37.5
2014 1      37.0  37.0
     2      36.0  36.0

For complicated records containing multiple labeled measurements across multiple
times for many subjects (people, countries, cities, etc.), use of hierarchical rows and
columns can be extremely convenient!

##### Indexing and Slicing a MultiIndex

Consider the multiply indexed Series of state populations

In [152]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [153]:
pop['California', 2000]

33871648

In [154]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [155]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [156]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [157]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [158]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

A multiply indexed DataFrame behaves in a similar manner.

In [159]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      38.0  37.9  23.0  35.8  33.0  38.7
     2      32.0  37.7  38.0  37.5  44.0  36.8
2014 1      44.0  37.4  37.0  37.0  16.0  36.6
     2      36.0  37.1  36.0  36.0  52.0  36.8

In [160]:
health_data['Guido', 'HR']

year  visit
2013  1        23.0
      2        38.0
2014  1        37.0
      2        36.0
Name: (Guido, HR), dtype: float64

In [161]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      38.0  37.9
     2      32.0  37.7

In [162]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        38.0
      2        32.0
2014  1        44.0
      2        36.0
Name: (Bob, HR), dtype: float64

##### Rearranging Multi-Indices

One of the keys to working with multiply indexed data is knowing how to effectively
transform the data. There are a number of operations that will preserve all the infor‐
mation in the dataset, but rearrange it for the purposes of various computations.

In [163]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.431802
      2      0.570806
c     1      0.030762
      2      0.646407
b     1      0.792274
      2      0.814173
dtype: float64

In [238]:
index

MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
           labels=[[0, 0, 2, 2, 1, 1], [0, 1, 0, 1, 0, 1]],
           names=['char', 'int'])

In [164]:
data = data.sort_index()
data

char  int
a     1      0.431802
      2      0.570806
b     1      0.792274
      2      0.814173
c     1      0.030762
      2      0.646407
dtype: float64

In [165]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [166]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [167]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

Another way to rearrange hierarchical data is to turn the index labels into columns;
this can be accomplished with the reset_index method

In [168]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [169]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

##### Data Aggregations on Multi-Indices

In [170]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      38.0  37.9  23.0  35.8  33.0  38.7
     2      32.0  37.7  38.0  37.5  44.0  36.8
2014 1      44.0  37.4  37.0  37.0  16.0  36.6
     2      36.0  37.1  36.0  36.0  52.0  36.8

In [171]:
#to average out the measurements in the two visits each year
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     35.0  37.80  30.5  36.65  38.5  37.75
2014     40.0  37.25  36.5  36.50  34.0  36.70

In [172]:
data_mean.mean(axis=1, level='type')

type         HR       Temp
year                      
2013  34.666667  37.400000
2014  36.833333  36.816667

### Combining Datasets: Concat and Append

Some of the most interesting studies of data come from combining different data
sources. These operations can involve anything from very straightforward concatena‐
tion of two different datasets, to more complicated database-style joins and merges
that correctly handle any overlaps between the datasets. Series and DataFrame s are
built with this type of operation in mind, and Pandas includes functions and methods
that make this sort of data wrangling fast and straightforward.

In [173]:
import pandas as pd
import numpy as np

In [174]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

Concatenation of Series and DataFrame objects is very similar to concatenation of
NumPy arrays

In [175]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
x = [[1, 2],
[3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

Pandas has a function, pd.concat() , which has a similar syntax to np.concatenate
but contains a number of options

In [177]:
# Signature in Pandas v0.18
# pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
# keys=None, levels=None, names=None, verify_integrity=False,
# copy=True)

pd.concat() can be used for a simple concatenation of Series or DataFrame objects,
just as np.concatenate() can be used for simple concatenations of arrays

In [239]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 3, 4])
ser2 = pd.Series(['D', 'E', 'F'], index=[2, 5, 6])
pd.concat([ser1, ser2])

1    A
3    B
4    C
2    D
5    E
6    F
dtype: object

In [179]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1)
print("\n")
print(df2)
print("\n")
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2


    A   B
3  A3  B3
4  A4  B4


    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


One important difference between np.concatenate and pd.concat is that Pandas
concatenation preserves indices, even if the result will have duplicate indices!

In [180]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

In [181]:
x

A   B
0  A0  B0
1  A1  B1

In [182]:
y

A   B
2  A2  B2
3  A3  B3

In [183]:
y.index = x.index # make duplicate indices!
print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


Notice the repeated indices in the result. While this is valid within DataFrame s, the
outcome is often undesirable. pd.concat() gives us a few ways to handle it.If you’d like to simply verify that the indices in the
result of pd.concat() do not overlap, you can specify the verify_integrity flag.
With this set to True , the concatenation will raise an exception if there are duplicate
indices.

In [184]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


Sometimes the index itself does not matter, and you would prefer
it to simply be ignored. You can specify this option using the ignore_index flag.

In [185]:
print(pd.concat([x, y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


Another alternative is to use the keys option to specify a label
for the data sources; the result will be a hierarchically indexed series containing the
data

In [186]:
print(pd.concat([x, y], keys=['x', 'y']))

      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


In [187]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5)
print("\n")
print(df6)
print("\n")
print(pd.concat([df5, df6],sort = True))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


    B   C   D
3  B3  C3  D3
4  B4  C4  D4


     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


By default, the entries for which no data is available are filled with NA values. To
change this, we can specify one of several options for the join and join_axes param‐
eters of the concatenate function. By default, the join is a union of the input columns
( join='outer' ), but we can change this to an intersection of the columns using
join='inner'

In [188]:
print(pd.concat([df5, df6], join='inner'))

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


Because direct array concatenation is so common, Series and DataFrame objects
have an append method that can accomplish the same thing in fewer keystrokes.Rather than calling pd.concat([df1, df2]) , you can simply call
df1.append(df2)

In [189]:
print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


Keep in mind that unlike the append() and extend() methods of Python lists, the
append() method in Pandas does not modify the original object—instead, it creates a
new object with the combined data. It also is not a very efficient method, because it
involves creation of a new index and data buffer. Thus, if you plan to do multiple
append operations, it is generally better to build a list of DataFrame s and pass them all
at once to the concat() function.

#### Merge and Join

One essential feature offered by Pandas is its high-performance, in-memory join and
merge operations.The pd.merge() function implements a number of types of joins: the one-to-one,
many-to-one, and many-to-many joins. All three types of joins are accessed via an
identical call to the pd.merge() interface; the type of join performed depends on the
form of the input data.

##### One-to-one joins

Perhaps the simplest type of merge expression is the one-to-one join, which is in
many ways very similar to the column-wise concatenation

In [190]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],'hire_date': [2004, 2008, 2012, 2014]})

In [191]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [192]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [193]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

The pd.merge() function recognizes that each DataFrame has an “employee” column,
and automatically joins using this column as a key. The result of the merge is a new
DataFrame that combines the information from the two inputs. Notice that the order
of entries in each column is not necessarily maintained: in this case, the order of the
“employee” column differs between df1 and df2 , and the pd.merge() function cor‐
rectly accounts for this. Additionally, keep in mind that the merge in general discards
the index, except in the special case of merges by index

##### Many-to-one joins

Many-to-one joins are joins in which one of the two key columns contains duplicate
entries. For the many-to-one case, the resulting DataFrame will preserve those dupli‐
cate entries as appropriate.

In [194]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],'supervisor': ['Carly', 'Guido', 'Steve']})
print(df4)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


In [195]:
print(pd.merge(df3, df4))

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


The resulting DataFrame has an additional column with the “supervisor” information,
where the information is repeated in one or more locations as required by the inputs.

##### Many-to-many joins

Many-to-many joins are a bit confusing conceptually, but are nevertheless well
defined. If the key column in both the left and right array contains duplicates, then
the result is a many-to-many merge.

In [196]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting','Engineering', 'Engineering', 'HR', 'HR'],'skills': ['math', 'spreadsheets', 'coding', 'linux','spreadsheets', 'organization']})

In [197]:
print(df1)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


In [198]:
print(df5)

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


In [199]:
print(pd.merge(df1, df5))

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


These three types of joins can be used with other Pandas tools to implement a wide
array of functionality.

##### Specification of the Merge Key

Most simply, you can explicitly specify the name of the key column using the on key‐
word, which takes a column name or a list of column names:

In [200]:
print(df1) 

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


In [201]:
print(df2) 

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [202]:
print(pd.merge(df1, df2, on='employee'))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


This option works only if both the left and right DataFrame s have the specified col‐
umn name.

At times you may wish to merge two datasets with different column names; for exam‐
ple, we may have a dataset in which the employee name is labeled as “name” rather
than “employee”. In this case, we can use the left_on and right_on keywords to
specify the two column names:

In [203]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],'salary': [70000, 80000, 120000, 90000]}) 

In [204]:
print(df3)

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


In [205]:
print(df1)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


In [206]:
pd.merge(df1, df3, left_on="employee", right_on="name")

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

The result has a redundant column that we can drop if desired—for example, by
using the drop() method of DataFrame s

In [207]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

Sometimes, rather than merging on a column, you would instead like to merge on an
index.

In [208]:
df1a = df1.set_index('employee')
df1a

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

In [209]:
df2a = df2.set_index('employee')
df2a

hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

the index as the key for merging by specifying the left_index and/or
right_index flags in pd.merge()


In [210]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

For convenience, DataFrame s implement the join() method, which performs a
merge that defaults to joining on indices

In [211]:
df1a.join(df2a)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [212]:
pd.merge(df1a, df3, left_index=True, right_on='name')

group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [213]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],'food': ['pizza', 'burger', 'sandwich']},columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],'drink': ['coke', 'pepsi']},columns=['name', 'drink'])

In [214]:
df6

name      food
0  Peter     pizza
1   Paul    burger
2   Mary  sandwich

In [215]:
df7

name  drink
0    Mary   coke
1  Joseph  pepsi

In [216]:
pd.merge(df6, df7)

name      food drink
0  Mary  sandwich  coke

In [217]:
pd.merge(df6, df7, how='inner')

name      food drink
0  Mary  sandwich  coke

In [218]:
pd.merge(df6, df7, how='outer')

name      food  drink
0   Peter     pizza    NaN
1    Paul    burger    NaN
2    Mary  sandwich   coke
3  Joseph       NaN  pepsi

In [219]:
pd.merge(df6, df7, how='left')

name      food drink
0  Peter     pizza   NaN
1   Paul    burger   NaN
2   Mary  sandwich  coke

In [220]:
pd.merge(df6, df7, how='right')

name      food  drink
0    Mary  sandwich   coke
1  Joseph       NaN  pepsi

Finally, you may end up in a case where your two input DataFrame s have conflicting
column names

In [221]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],'rank': [3, 1, 4, 2]})

In [222]:
pd.merge(df8, df9, on="name")

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [223]:
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [224]:
# read data from csv

In [240]:
pop = pd.read_csv('state-population.cs.v')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

### Aggregation and Grouping

An essential piece of analysis of large data is efficient summarization: computing
aggregations like sum() , mean() , median() , min() , and max() , in which a single num‐
ber gives insight into the nature of a potentially large dataset.

In [242]:
df = pd.DataFrame({'A': rng.rand(5),'B': rng.rand(5)})
df

A         B
0  0.965632  0.440152
1  0.808397  0.122038
2  0.304614  0.495177
3  0.097672  0.034389
4  0.684233  0.909320

In [243]:
df.mean()

A    0.572110
B    0.400215
dtype: float64

In [244]:
df.mean(axis='columns')

0    0.702892
1    0.465218
2    0.399895
3    0.066030
4    0.796777
dtype: float64

In [245]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [283]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [247]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

This can be a useful way to begin understanding the overall properties of a dataset.

### GroupBy: Split, Apply, Combine

Simple aggregations can give you a flavor of your dataset, but often we would prefer
to aggregate conditionally on some label or index: this is implemented in the so-
called groupby operation.

• The split step involves breaking up and grouping a DataFrame depending on the
value of the specified key.

• The apply step involves computing some function, usually an aggregate, transfor‐
mation, or filtering, within the individual groups.

• The combine step merges the results of these operations into an output array.

In [249]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [250]:
df.groupby('key')

Notice that what is returned is not a set of DataFrame s, but a DataFrameGroupBy
object. This object is where the magic is: you can think of it as a special view of the
DataFrame , which is poised to dig into the groups but does no actual computation
until the aggregation is applied. This “lazy evaluation” approach means that common
aggregates can be implemented very efficiently in a way that is almost transparent to
the user.
To produce a result, we can apply an aggregate to this DataFrameGroupBy object,
which will perform the appropriate apply/combine steps to produce the desired
result

In [251]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [252]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [284]:
planets["method"].value_counts()

Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: method, dtype: int64

In [285]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [253]:
planets.groupby('method')['year'].describe()

count         mean       std     min      25%  \
method                                                                         
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75   
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00   
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00   
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00   
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00   
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00   
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00   
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00   
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00   
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75   

                                  50%      75%     max  
method                                                  
Astrometry                     2011.5  2012.25  2013.0  
Eclipse Timing Variations      2010.0  2011.00  2012.0  
Imaging                        2009.0  2011.00  2013.0  
Microlensing                   2010.0  2012.00  2013.0  
Orbital Brightness Modulation  2011.0  2012.00  2013.0  
Pulsar Timing                  1994.0  2003.00  2011.0  
Pulsation Timing Variations    2007.0  2007.00  2007.0  
Radial Velocity                2009.0  2011.00  2014.0  
Transit                        2012.0  2013.00  2014.0  
Transit Timing Variations      2012.5  2013.25  2014.0

In [304]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],'data1': range(6),'data2': rng.randint(0, 10, 6)},columns = ['key', 'data1', 'data2'])
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

The aggregate() method allows for even more flexibility, it can take
a string, a function, or a list thereof, and compute all the aggregates at once.

In [305]:
df.groupby('key').aggregate(['min', np.median, max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [306]:
df.groupby('key').aggregate({'data1': 'min','data2': 'max'})

data1  data2
key              
A        0      5
B        1      7
C        2      9

Filtering. A filtering operation allows you to drop data based on the group properties.

In [307]:
def filter_func(x):
    return x['data2'].std() > 4

print(df.groupby('key'))
print(df.groupby('key').std())
print(df.groupby('key').filter(filter_func))

       data1     data2
key                   
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641
  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9


In [308]:
filter_func(df)

False

In [309]:
filter_func(df.groupby('key'))

key
A    False
B     True
C     True
Name: data2, dtype: bool

Transformation. While aggregation must return a reduced version of the data, trans‐
formation can return some transformed version of the full data to recombine. For
such a transformation, the output is the same shape as the input.

In [310]:
df.groupby('key').transform(lambda x: x - x.mean())

data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

The apply() method. The apply() method lets you apply an arbitrary function to the
group results. The function should take a DataFrame , and return either a Pandas
object (e.g., DataFrame , Series ) or a scalar; the combine operation will be tailored to
the type of output returned.

In [311]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

print(df)
print(df.groupby('key').apply(norm_by_data2))

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9
  key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9


### Pivot Tables

The GroupBy abstraction lets us explore relationships within a data‐
set. A pivot table is a similar operation that is commonly seen in spreadsheets and
other programs that operate on tabular data. The pivot table takes simple column-
wise data as input, and groups the entries into a two-dimensional table that provides
a multidimensional summarization of the data.

In [261]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [262]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [263]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

This is useful, but we might like to go one step deeper and look at survival by both sex
and, say, class.

In [264]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

This gives us a better idea of how both gender and class affected survival, but the
code is starting to look a bit garbled.

In [265]:
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [266]:

# DataFrame.pivot_table(data, values=None, index=None, columns=None,
# aggfunc='mean', fill_value=None, margins=False,
# dropna=True, margins_name='All')

At times it’s useful to compute totals along each grouping.

In [267]:
titanic.pivot_table('survived', index='sex', columns='class', margins=True)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

### Working with Time Series

In [268]:
from datetime import datetime
datetime(year=2015, month=7, day=4)

datetime.datetime(2015, 7, 4, 0, 0)

In [269]:
from dateutil import parser
date = parser.parse("4th of July, 2015")
date

datetime.datetime(2015, 7, 4, 0, 0)

In [271]:
import numpy as np
date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [272]:
date + np.arange(12)

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

Pandas can construct a DatetimeIndex that can be used to index data in a Series or
DataFrame

In [273]:
import pandas as pd
date = pd.to_datetime("4th of July, 2015")
date

Timestamp('2015-07-04 00:00:00')

In [274]:
date + pd.to_timedelta(np.arange(12), 'D')

DatetimeIndex(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
               '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
               '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
              dtype='datetime64[ns]', freq=None)

In [275]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04','2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [276]:
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [277]:
data['2015']

2015-07-04    2
2015-08-04    3
dtype: int64

In [278]:
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015','2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[ns]', freq=None)

In [279]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [280]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [281]:
pd.date_range('2015-07-03', periods=8, freq='H')

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')